version: '3'
services:
  db:
    container_name: fantasy_baseball_db
    image: mysql:5.7
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root