version: '3'
services:
  db:
    container_name: fantasy_baseball_db
    image: mysql
    command: --secure-file-priv=/data --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./data:/data
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build: ./
    links:
      - db
    volumes:
      - ./src:/app
    ports:
      - 8080:8080