FROM continuumio/anaconda3

#RUN apt-get update \
#  && apt-get install -y python3-pip python3-dev \
#  && cd /usr/local/bin \
#  && ln -s /usr/bin/python3 python \
#  && pip3 install --upgrade pip 
# && apt-get install sqlite3 libsqlite3-dev

#ADD start.py /

#CMD [ "python3", "./start.py" ]

#RUN mkdir /db
WORKDIR /app

RUN pip install flask

COPY src /app

#ENTRYPOINT ["sqlite3"]
#CMD ["test.db"]

EXPOSE 8080
CMD [ "python3", "server.py" ]