CREATE SCHEMA dbo;
USE dbo;
CREATE TABLE dbo.BattingDemo(
Season INTEGER
,Name VARCHAR(64)
,Team VARCHAR(64)
,Age INTEGER
,G INTEGER 
,AB INTEGER
,PA INTEGER
,H INTEGER
,1B INTEGER
,2B INTEGER
,3B INTEGER
,HR INTEGER
,R INTEGER
,RBI INTEGER
,BB INTEGER
,IBB INTEGER
,SO INTEGER
,HBP INTEGER
,SF INTEGER
,SH INTEGER
,GDP INTEGER
,SB INTEGER
,CS INTEGER
,AVG DECIMAL(10,4)
,GB DECIMAL(10,4)
,FB DECIMAL(10,4)
,LD DECIMAL(10,4)
,IFFB DECIMAL(10,4)
,Pitches DECIMAL(10,4)
,Balls DECIMAL(10,4)
,Strikes DECIMAL(10,4) )