SET GLOBAL local_infile = 'ON';
CREATE SCHEMA dbo;
USE dbo;
CREATE TABLE dbo.Batting(
Season INTEGER
,Name VARCHAR(64)
,Team VARCHAR(64)
,Age INTEGER
,G INTEGER 
,AB INTEGER
,PA INTEGER
,H INTEGER
,1B INTEGER
,2B INTEGER
,3B INTEGER
,HR INTEGER
,R INTEGER
,RBI INTEGER
,BB INTEGER
,IBB INTEGER
,SO INTEGER
,HBP INTEGER
,SF INTEGER
,SH INTEGER
,GDP INTEGER
,SB INTEGER
,CS INTEGER
,AVG DECIMAL(10,4)
,GB INTEGER
,FB INTEGER
,LD INTEGER
,IFFB INTEGER
,Pitches INTEGER
,Balls INTEGER
,Strikes INTEGER );

CREATE TABLE dbo.Pitching(
Season INTEGER
,Name VARCHAR(64)
,Team VARCHAR(64)
,Age INTEGER
,W INTEGER 
,L INTEGER
,ERA DECIMAL(10,4)
,WAR DECIMAL(10,4)
,G INTEGER
,GS INTEGER
,CG INTEGER
,ShO INTEGER
,SV INTEGER
,BS INTEGER
,IP DECIMAL(10,4)
,TBF INTEGER
,H INTEGER
,R INTEGER
,ER INTEGER
,HR INTEGER
,BB INTEGER
,IBB INTEGER
,HBP INTEGER
,WP INTEGER
,BK INTEGER
,SO INTEGER
,GB INTEGER
,FB INTEGER
,LD INTEGER
,IFFB INTEGER
,Balls INTEGER
,Strikes INTEGER
,Pitches INTEGER );

LOAD DATA INFILE '/data/batting_data_1996_2019.csv'
INTO TABLE dbo.Batting
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Season,@Name,@Team,@Age,@G,@AB,@PA,@H,@1B,@2B,@3B,@HR,@R,@RBI,@BB,@IBB,@SO,@HBP,@SF,@SH,@GDP,@SB,@CS,@AVG,@GB,@FB,@LD,@IFFB,@Pitches,@Balls,@Strikes)
SET Season = CASE WHEN @Season = '' THEN NULL ELSE @Season END,
Name = CASE WHEN @Name = '' THEN NULL ELSE @Name END,
Team = CASE WHEN @Team = '' THEN NULL ELSE @Team END,
Age = CASE WHEN @Age = '' THEN NULL ELSE @Age END,
G = CASE WHEN @G = '' THEN NULL ELSE @G END,
AB = CASE WHEN @AB = '' THEN NULL ELSE @AB END,
PA = CASE WHEN @PA = '' THEN NULL ELSE @PA END,
H = CASE WHEN @H = '' THEN NULL ELSE @H END,
1B = CASE WHEN @1B = '' THEN NULL ELSE @1B END,
2B = CASE WHEN @2B = '' THEN NULL ELSE @2B END,
3B = CASE WHEN @3B = '' THEN NULL ELSE @3B END,
HR = CASE WHEN @HR = '' THEN NULL ELSE @HR END,
R = CASE WHEN @R = '' THEN NULL ELSE @R END,
RBI = CASE WHEN @RBI = '' THEN NULL ELSE @RBI END,
BB = CASE WHEN @BB = '' THEN NULL ELSE @BB END,
IBB = CASE WHEN @IBB = '' THEN NULL ELSE @IBB END,
SO = CASE WHEN @SO = '' THEN NULL ELSE @SO END,
HBP = CASE WHEN @HBP = '' THEN NULL ELSE @HBP END,
SF = CASE WHEN @SF = '' THEN NULL ELSE @SF END,
SH = CASE WHEN @SH = '' THEN NULL ELSE @SH END,
GDP = CASE WHEN @GDP = '' THEN NULL ELSE @GDP END,
SB = CASE WHEN @SB = '' THEN NULL ELSE @SB END,
CS = CASE WHEN @CS = '' THEN NULL ELSE @CS END,
AVG = CASE WHEN @AVG = '' THEN NULL ELSE @AVG END,
GB = CASE WHEN @GB = '' THEN NULL ELSE @GB END,
FB = CASE WHEN @FB = '' THEN NULL ELSE @FB END,
LD = CASE WHEN @LD = '' THEN NULL ELSE @LD END,
IFFB = CASE WHEN @IFFB = '' THEN NULL ELSE @IFFB END,
Pitches = CASE WHEN @Pitches = '' THEN NULL ELSE @Pitches END,
Balls = CASE WHEN @Balls = '' THEN NULL ELSE @Balls END,
Strikes = CASE WHEN @Strikes = '' THEN NULL ELSE @Strikes END;

LOAD DATA INFILE '/data/pitching_data_1996_2019.csv'
INTO TABLE dbo.Pitching
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Season,@Name,@Team,@Age,@W,@L,@ERA,@WAR,@G,@GS,@CG,@ShO,@SV,@BS,@IP,@TBF,@H,@R,@ER,@HR,@BB,@IBB,@HBP,@WP,@BK,@SO,@GB,@FB,@LD,@IFFB,@Balls,@Strikes,@Pitches)
SET Season = CASE WHEN @Season = '' THEN NULL ELSE @Season END,
Name = CASE WHEN @Name = '' THEN NULL ELSE @Name END,
Team = CASE WHEN @Team = '' THEN NULL ELSE @Team END,
Age = CASE WHEN @Age = '' THEN NULL ELSE @Age END,
W = CASE WHEN @W = '' THEN NULL ELSE @W END,
L = CASE WHEN @L = '' THEN NULL ELSE @L END,
ERA = CASE WHEN @ERA = '' THEN NULL ELSE @ERA END,
WAR = CASE WHEN @WAR = '' THEN NULL ELSE @WAR END,
G = CASE WHEN @G = '' THEN NULL ELSE @G END,
GS = CASE WHEN @GS = '' THEN NULL ELSE @GS END,
CG = CASE WHEN @CG = '' THEN NULL ELSE @CG END,
ShO = CASE WHEN @ShO = '' THEN NULL ELSE @ShO END,
SV = CASE WHEN @SV = '' THEN NULL ELSE @SV END,
BS = CASE WHEN @BS = '' THEN NULL ELSE @BS END,
IP = CASE WHEN @IP = '' THEN NULL ELSE @IP END,
TBF = CASE WHEN @TBF = '' THEN NULL ELSE @TBF END,
H = CASE WHEN @H = '' THEN NULL ELSE @H END,
R = CASE WHEN @R = '' THEN NULL ELSE @R END,
ER = CASE WHEN @ER = '' THEN NULL ELSE @ER END,
HR = CASE WHEN @HR = '' THEN NULL ELSE @HR END,
BB = CASE WHEN @BB = '' THEN NULL ELSE @BB END,
IBB = CASE WHEN @IBB = '' THEN NULL ELSE @IBB END,
HBP = CASE WHEN @HBP = '' THEN NULL ELSE @HBP END,
WP = CASE WHEN @WP = '' THEN NULL ELSE @WP END,
BK = CASE WHEN @BK = '' THEN NULL ELSE @BK END,
SO = CASE WHEN @SO = '' THEN NULL ELSE @SO END,
GB = CASE WHEN @GB = '' THEN NULL ELSE @GB END,
FB = CASE WHEN @FB = '' THEN NULL ELSE @FB END,
LD = CASE WHEN @LD = '' THEN NULL ELSE @LD END,
IFFB = CASE WHEN @IFFB = '' THEN NULL ELSE @IFFB END,
Balls = CASE WHEN @Balls = '' THEN NULL ELSE @Balls END,
Strikes = CASE WHEN @Strikes = '' THEN NULL ELSE @Strikes END,
Pitches = CASE WHEN @Pitches = '' THEN NULL ELSE @Pitches END;
