SET GLOBAL local_infile = 'ON';
CREATE SCHEMA dbo;
USE dbo;
CREATE TABLE dbo.Batting(
Season INTEGER
,Name VARCHAR(64)
,HR INTEGER 
,HR_LOW INTEGER
,HR_MED INTEGER
,HR_HIGH INTEGER
,TB INTEGER
,TB_LOW INTEGER
,TB_MED INTEGER
,TB_HIGH INTEGER
,R INTEGER
,R_LOW INTEGER
,R_MED INTEGER
,R_HIGH INTEGER
,RBI INTEGER
,RBI_LOW INTEGER
,RBI_MED INTEGER
,RBI_HIGH INTEGER
,SB INTEGER
,SB_LOW INTEGER
,SB_MED INTEGER
,SB_HIGH INTEGER
,AVG DECIMAL(10,4)
,AVG_LOW INTEGER
,AVG_MED INTEGER
,AVG_HIGH INTEGER
,OBP DECIMAL(10,4)
,OBP_LOW INTEGER
,OBP_MED INTEGER
,OBP_HIGH INTEGER
,SLG DECIMAL(10,4)
,SLG_LOW INTEGER
,SLG_MED INTEGER
,SLG_HIGH INTEGER
,key_mlbam INTEGER
,overall_risk INTEGER);

CREATE TABLE dbo.Pitching(
Season INTEGER
,Name VARCHAR(64)
,W INTEGER
,W_LOW INTEGER
,W_MED INTEGER
,W_HIGH INTEGER
,L INTEGER
,L_LOW INTEGER
,L_MED INTEGER
,L_HIGH INTEGER
,ERA DECIMAL(10,4)
,ERA_LOW INTEGER
,ERA_MED INTEGER
,ERA_HIGH INTEGER
,SV INTEGER
,SV_LOW INTEGER
,SV_MED INTEGER
,SV_HIGH INTEGER
,IP DECIMAL(10,4)
,IP_LOW INTEGER
,IP_MED INTEGER
,IP_HIGH INTEGER
,HR INTEGER
,HR_LOW INTEGER
,HR_MED INTEGER
,HR_HIGH INTEGER
,SO INTEGER
,SO_LOW INTEGER
,SO_MED INTEGER
,SO_HIGH INTEGER
,WHIP DECIMAL(10,4)
,WHIP_LOW INTEGER
,WHIP_MED INTEGER
,WHIP_HIGH INTEGER
,key_mlbam INTEGER
,overall_risk INTEGER
,pitcher_type VARCHAR(16));

LOAD DATA INFILE '/data/batting_data_1996_2020_with_risk.csv'
INTO TABLE dbo.Batting
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Season,@Name,@HR,@HR_LOW,@HR_MED,@HR_HIGH,@TB,@TB_LOW,@TB_MED,@TB_HIGH,@R,@R_LOW,@R_MED,@R_HIGH,@RBI,@RBI_LOW,@RBI_MED,@RBI_HIGH,@SB,@SB_LOW,@SB_MED,@SB_HIGH,@AVG,@AVG_LOW,@AVG_MED,@AVG_HIGH,@OBP,@OBP_LOW,@OBP_MED,@OBP_HIGH,@SLG,@SLG_LOW,@SLG_MED,@SLG_HIGH,@key_mlbam,@overall_risk)
SET Season = CASE WHEN @Season = '' THEN NULL ELSE @Season END,
Name = CASE WHEN @Name = '' THEN NULL ELSE @Name END,
HR = CASE WHEN @HR = '' THEN NULL ELSE @HR END,
HR_LOW = CASE WHEN @HR_LOW = '' THEN NULL ELSE @HR_LOW END,
HR_MED = CASE WHEN @HR_MED = '' THEN NULL ELSE @HR_MED END,
HR_HIGH = CASE WHEN @HR_HIGH = '' THEN NULL ELSE @HR_HIGH END,
TB = CASE WHEN @TB = '' THEN NULL ELSE @TB END,
TB_LOW = CASE WHEN @TB_LOW = '' THEN NULL ELSE @TB_LOW END,
TB_MED = CASE WHEN @TB_MED = '' THEN NULL ELSE @TB_MED END,
TB_HIGH = CASE WHEN @TB_HIGH = '' THEN NULL ELSE @TB_HIGH END,
R = CASE WHEN @R = '' THEN NULL ELSE @R END,
R_LOW = CASE WHEN @R_LOW = '' THEN NULL ELSE @R_LOW END,
R_MED = CASE WHEN @R_MED = '' THEN NULL ELSE @R_MED END,
R_HIGH = CASE WHEN @R_HIGH = '' THEN NULL ELSE @R_HIGH END,
RBI = CASE WHEN @RBI = '' THEN NULL ELSE @RBI END,
RBI_LOW = CASE WHEN @RBI_LOW = '' THEN NULL ELSE @RBI_LOW END,
RBI_MED = CASE WHEN @RBI_MED = '' THEN NULL ELSE @RBI_MED END,
RBI_HIGH = CASE WHEN @RBI_HIGH = '' THEN NULL ELSE @RBI_HIGH END,
SB = CASE WHEN @SB = '' THEN NULL ELSE @SB END,
SB_LOW = CASE WHEN @SB_LOW = '' THEN NULL ELSE @SB_LOW END,
SB_MED = CASE WHEN @SB_MED = '' THEN NULL ELSE @SB_MED END,
SB_HIGH = CASE WHEN @SB_HIGH = '' THEN NULL ELSE @SB_HIGH END,
AVG = CASE WHEN @AVG = '' THEN NULL ELSE @AVG END,
AVG_LOW = CASE WHEN @AVG_LOW = '' THEN NULL ELSE @AVG_LOW END,
AVG_MED = CASE WHEN @AVG_MED = '' THEN NULL ELSE @AVG_MED END,
AVG_HIGH = CASE WHEN @AVG_HIGH = '' THEN NULL ELSE @AVG_HIGH END,
OBP = CASE WHEN @OBP = '' THEN NULL ELSE @OBP END,
OBP_LOW = CASE WHEN @OBP_LOW = '' THEN NULL ELSE @OBP_LOW END,
OBP_MED = CASE WHEN @OBP_MED = '' THEN NULL ELSE @OBP_MED END,
OBP_HIGH = CASE WHEN @OBP_HIGH = '' THEN NULL ELSE @OBP_HIGH END,
SLG = CASE WHEN @SLG = '' THEN NULL ELSE @SLG END,
SLG_LOW = CASE WHEN @SLG_LOW = '' THEN NULL ELSE @SLG_LOW END,
SLG_MED = CASE WHEN @SLG_MED = '' THEN NULL ELSE @SLG_MED END,
SLG_HIGH = CASE WHEN @SLG_HIGH = '' THEN NULL ELSE @SLG_HIGH END,
key_mlbam = CASE WHEN @key_mlbam = '' THEN NULL ELSE @key_mlbam END,
overall_risk = CASE WHEN @overall_risk = '' THEN NULL ELSE @overall_risk END;

LOAD DATA INFILE '/data/pitching_data_relievers_1996_2020_with_risk.csv'
INTO TABLE dbo.Pitching
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Season,@Name,@W,@W_LOW,@W_MED,@W_HIGH,@L,@L_LOW,@L_MED,@L_HIGH,@ERA,@ERA_LOW,@ERA_MED,@ERA_HIGH,@SV,@SV_LOW,@SV_MED,@SV_HIGH,@IP,@IP_LOW,@IP_MED,@IP_HIGH,@HR,@HR_LOW,@HR_MED,@HR_HIGH,@SO,@SO_LOW,@SO_MED,@SO_HIGH,@WHIP,@WHIP_LOW,@WHIP_MED,@WHIP_HIGH,@key_mlbam,@overall_risk)
SET Season = CASE WHEN @Season = '' THEN NULL ELSE @Season END,
Name = CASE WHEN @Name = '' THEN NULL ELSE @Name END,
W = CASE WHEN @W = '' THEN NULL ELSE @W END,
W_LOW = CASE WHEN @W_LOW = '' THEN NULL ELSE @W_LOW END,
W_MED = CASE WHEN @W_MED = '' THEN NULL ELSE @W_MED END,
W_HIGH = CASE WHEN @W_HIGH = '' THEN NULL ELSE @W_HIGH END,
L = CASE WHEN @L = '' THEN NULL ELSE @L END,
L_LOW = CASE WHEN @L_LOW = '' THEN NULL ELSE @L_LOW END,
L_MED = CASE WHEN @L_MED = '' THEN NULL ELSE @L_MED END,
L_HIGH = CASE WHEN @L_HIGH = '' THEN NULL ELSE @L_HIGH END,
ERA = CASE WHEN @ERA = '' THEN NULL ELSE @ERA END,
ERA_LOW = CASE WHEN @ERA_LOW = '' THEN NULL ELSE @ERA_LOW END,
ERA_MED = CASE WHEN @ERA_MED = '' THEN NULL ELSE @ERA_MED END,
ERA_HIGH = CASE WHEN @ERA_HIGH = '' THEN NULL ELSE @ERA_HIGH END,
SV = CASE WHEN @SV = '' THEN NULL ELSE @SV END,
SV_LOW = CASE WHEN @SV_LOW = '' THEN NULL ELSE @SV_LOW END,
SV_MED = CASE WHEN @SV_MED = '' THEN NULL ELSE @SV_MED END,
SV_HIGH = CASE WHEN @SV_HIGH = '' THEN NULL ELSE @SV_HIGH END,
IP = CASE WHEN @IP = '' THEN NULL ELSE @IP END,
IP_LOW = CASE WHEN @IP_LOW = '' THEN NULL ELSE @IP_LOW END,
IP_MED = CASE WHEN @IP_MED = '' THEN NULL ELSE @IP_MED END,
IP_HIGH = CASE WHEN @IP_HIGH = '' THEN NULL ELSE @IP_HIGH END,
HR = CASE WHEN @HR = '' THEN NULL ELSE @HR END,
HR_LOW = CASE WHEN @HR_LOW = '' THEN NULL ELSE @HR_LOW END,
HR_MED = CASE WHEN @HR_MED = '' THEN NULL ELSE @HR_MED END,
HR_HIGH = CASE WHEN @HR_HIGH = '' THEN NULL ELSE @HR_HIGH END,
SO = CASE WHEN @SO = '' THEN NULL ELSE @SO END,
SO_LOW = CASE WHEN @SO_LOW = '' THEN NULL ELSE @SO_LOW END,
SO_MED = CASE WHEN @SO_MED = '' THEN NULL ELSE @SO_MED END,
SO_HIGH = CASE WHEN @SO_HIGH = '' THEN NULL ELSE @SO_HIGH END,
WHIP = CASE WHEN @WHIP = '' THEN NULL ELSE @WHIP END,
WHIP_LOW = CASE WHEN @WHIP_LOW = '' THEN NULL ELSE @WHIP_LOW END,
WHIP_MED = CASE WHEN @WHIP_MED = '' THEN NULL ELSE @WHIP_MED END,
WHIP_HIGH = CASE WHEN @WHIP_HIGH = '' THEN NULL ELSE @WHIP_HIGH END,
key_mlbam = CASE WHEN @key_mlbam = '' THEN NULL ELSE @key_mlbam END,
overall_risk = CASE WHEN @overall_risk = '' THEN NULL ELSE @overall_risk END,
pitcher_type = 'Reliever';

LOAD DATA INFILE '/data/pitching_data_starters_1996_2020_with_risk.csv'
INTO TABLE dbo.Pitching
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Season,@Name,@W,@W_LOW,@W_MED,@W_HIGH,@L,@L_LOW,@L_MED,@L_HIGH,@ERA,@ERA_LOW,@ERA_MED,@ERA_HIGH,@SV,@SV_LOW,@SV_MED,@SV_HIGH,@IP,@IP_LOW,@IP_MED,@IP_HIGH,@HR,@HR_LOW,@HR_MED,@HR_HIGH,@SO,@SO_LOW,@SO_MED,@SO_HIGH,@WHIP,@WHIP_LOW,@WHIP_MED,@WHIP_HIGH,@key_mlbam,@overall_risk)
SET Season = CASE WHEN @Season = '' THEN NULL ELSE @Season END,
Name = CASE WHEN @Name = '' THEN NULL ELSE @Name END,
W = CASE WHEN @W = '' THEN NULL ELSE @W END,
W_LOW = CASE WHEN @W_LOW = '' THEN NULL ELSE @W_LOW END,
W_MED = CASE WHEN @W_MED = '' THEN NULL ELSE @W_MED END,
W_HIGH = CASE WHEN @W_HIGH = '' THEN NULL ELSE @W_HIGH END,
L = CASE WHEN @L = '' THEN NULL ELSE @L END,
L_LOW = CASE WHEN @L_LOW = '' THEN NULL ELSE @L_LOW END,
L_MED = CASE WHEN @L_MED = '' THEN NULL ELSE @L_MED END,
L_HIGH = CASE WHEN @L_HIGH = '' THEN NULL ELSE @L_HIGH END,
ERA = CASE WHEN @ERA = '' THEN NULL ELSE @ERA END,
ERA_LOW = CASE WHEN @ERA_LOW = '' THEN NULL ELSE @ERA_LOW END,
ERA_MED = CASE WHEN @ERA_MED = '' THEN NULL ELSE @ERA_MED END,
ERA_HIGH = CASE WHEN @ERA_HIGH = '' THEN NULL ELSE @ERA_HIGH END,
SV = CASE WHEN @SV = '' THEN NULL ELSE @SV END,
SV_LOW = CASE WHEN @SV_LOW = '' THEN NULL ELSE @SV_LOW END,
SV_MED = CASE WHEN @SV_MED = '' THEN NULL ELSE @SV_MED END,
SV_HIGH = CASE WHEN @SV_HIGH = '' THEN NULL ELSE @SV_HIGH END,
IP = CASE WHEN @IP = '' THEN NULL ELSE @IP END,
IP_LOW = CASE WHEN @IP_LOW = '' THEN NULL ELSE @IP_LOW END,
IP_MED = CASE WHEN @IP_MED = '' THEN NULL ELSE @IP_MED END,
IP_HIGH = CASE WHEN @IP_HIGH = '' THEN NULL ELSE @IP_HIGH END,
HR = CASE WHEN @HR = '' THEN NULL ELSE @HR END,
HR_LOW = CASE WHEN @HR_LOW = '' THEN NULL ELSE @HR_LOW END,
HR_MED = CASE WHEN @HR_MED = '' THEN NULL ELSE @HR_MED END,
HR_HIGH = CASE WHEN @HR_HIGH = '' THEN NULL ELSE @HR_HIGH END,
SO = CASE WHEN @SO = '' THEN NULL ELSE @SO END,
SO_LOW = CASE WHEN @SO_LOW = '' THEN NULL ELSE @SO_LOW END,
SO_MED = CASE WHEN @SO_MED = '' THEN NULL ELSE @SO_MED END,
SO_HIGH = CASE WHEN @SO_HIGH = '' THEN NULL ELSE @SO_HIGH END,
WHIP = CASE WHEN @WHIP = '' THEN NULL ELSE @WHIP END,
WHIP_LOW = CASE WHEN @WHIP_LOW = '' THEN NULL ELSE @WHIP_LOW END,
WHIP_MED = CASE WHEN @WHIP_MED = '' THEN NULL ELSE @WHIP_MED END,
WHIP_HIGH = CASE WHEN @WHIP_HIGH = '' THEN NULL ELSE @WHIP_HIGH END,
key_mlbam = CASE WHEN @key_mlbam = '' THEN NULL ELSE @key_mlbam END,
overall_risk = CASE WHEN @overall_risk = '' THEN NULL ELSE @overall_risk END,
pitcher_type = 'Starter';
